ARG BASE_IMAGE=ubuntu:24.04

FROM ${BASE_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential cmake pkg-config libssl-dev libzmq3-dev libunbound-dev libsodium-dev \
    libunwind8-dev liblzma-dev libreadline6-dev libexpat1-dev libpgm-dev \
    qttools5-dev-tools libhidapi-dev libusb-1.0-0-dev \
    libprotobuf-dev protobuf-compiler libudev-dev libzstd-dev \
    libboost-chrono-dev libboost-date-time-dev libboost-filesystem-dev \
    libboost-locale-dev libboost-program-options-dev libboost-regex-dev \
    libboost-serialization-dev libboost-system-dev libboost-thread-dev \
    python3 python3-pip python3-all python3-pybind11 python3-pytest python3-pytest-rerunfailures \
    ccache doxygen graphviz git curl autoconf libtool gperf nettle-dev libevent-dev \
    debhelper bison flex wget \
 && ldconfig \
 && rm -rf /var/lib/apt/lists/*

RUN . /etc/os-release && \
    if [ "$VERSION_CODENAME" = "jammy" ]; then \
        pip3 install scikit-build-core; \
    else \
        pip3 install scikit-build-core --break-system-packages; \
    fi

RUN wget https://github.com/libexpat/libexpat/releases/download/R_2_7_1/expat-2.7.1.tar.bz2 \
 && echo "45c98ae1e9b5127325d25186cf8c511fa814078e9efeae7987a574b482b79b3d  expat-2.7.1.tar.bz2" | sha256sum -c \
 && tar -xf expat-2.7.1.tar.bz2 \
 && cd expat-2.7.1 \
 && ./configure --enable-static --disable-shared --with-pic \
 && make -j$(nproc) && make install \
 && cd .. && rm -rf expat-2.7.1*

RUN wget https://www.nlnetlabs.nl/downloads/unbound/unbound-1.22.0.tar.gz \
 && echo "c5dd1bdef5d5685b2cedb749158dd152c52d44f65529a34ac15cd88d4b1b3d43  unbound-1.22.0.tar.gz" | sha256sum -c \
 && tar xzf unbound-1.22.0.tar.gz \
 && cd unbound-1.22.0 \
 && ./configure --with-libexpat=/usr/local --with-ssl=/usr --enable-static --disable-shared --with-pic \
 && make -j$(nproc) && make install \
 && cd .. && rm -rf unbound-1.22.0*

RUN git config --global --add safe.directory '*'

WORKDIR /monero-python
